const SET_CURRENCIES = 'SET_CURRENCIES',
      IS_FETCHING_CURRENCIES = 'IS_FETCHING_CURRENCIES',
      IS_ERROR_FETCHING_CURRENCIES = 'IS_ERROR_FETCHING_CURRENCIES',
      SET_GLOBAL_DATA = 'SET_GLOBAL_DATA',
      IS_FETCHING_GLOBAL_DATA = 'IS_FETCHING_GLOBAL_DATA',
      IS_ERROR_FETCHING_GLOBAL_DATA = 'IS_ERROR_FETCHING_GLOBAL_DATA'

export {
  SET_CURRENCIES,
  IS_FETCHING_CURRENCIES,
  IS_ERROR_FETCHING_CURRENCIES,
  SET_GLOBAL_DATA,
  IS_FETCHING_GLOBAL_DATA,
  IS_ERROR_FETCHING_GLOBAL_DATA
}