const SET_CURRENCIES = 'SET_CURRENCIES',
      IS_FETCHING_CURRENCIES = 'IS_FETCHING_CURRENCIES',
      IS_ERROR_FETCHING_CURRENCIES = 'IS_ERROR_FETCHING_CURRENCIES'

export {
  SET_CURRENCIES,
  IS_FETCHING_CURRENCIES,
  IS_ERROR_FETCHING_CURRENCIES
}